### PR TITLE
BUGFIX(netdata): Fix ZooKeeper metrics gathering, …

### PR DESCRIPTION
**Pull request by vincent-legoll**
##### SUMMARY
Pattern matching was too strict

This should go along with 05a3bebcfbbb2cc2d4ed0258ef93bb0b1b88bf84 from grafana role

 ##### ISSUE TYPE
- Bugfix Pull Request

 ##### SCOPE (skeleton only)
- SDS

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by vincent-legoll** [comment]
For CI to pass we first need to merge : https://github.com/open-io/ansible-role-openio-netdata/pull/28

**Comment by vincent-legoll** [comment]
@vdombrovski CI is now passing, so could you tell if this is sufficient assuming the grafana role is above 05a3bebcfbbb2cc2d4ed0258ef93bb0b1b88bf84

**Comment by cdelgehier** [comment]
Can you squash commit ?

**Comment by vincent-legoll** [comment]
No, I prefer to keep cosmetic changes separated from functional ones, for commit message readability's sake.

**Pull request merged**
