### PR TITLE
CHANGE(netdata): set max open file for netdata processes

### PR DESCRIPTION
**Pull request by fatpat**
##### SUMMARY

set the max open file parameter (`LimitNOFILE`) in the systemd service
file with `30000` by default (can be changed through variable
`openio_netdata_nofile`).

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION
Jira R1910-32

### CODE REVIEW

**Comment by vdombrovski** [comment]
This change might break with a package update, and should not be considered as a definitive fix. This parameter should be provided directly via the package.

**Review by vdombrovski — APPROVED** [review]

**Comment by fatpat** [comment]
OK I'll make this change in the packages instead of in the role. This makes sens.

**Comment by fatpat** [comment]
RPM: https://github.com/open-io/rpm-specfiles/pull/240
DEB: https://github.com/open-io/deb-packaging/pull/140

**Comment by fatpat** [comment]
this has been moved to the package

**Pull request closed without merging**
